### ISSUE TITLE
Can't connect to Core during "spend"

### ISSUE THREAD

**Issue by GilAlexander** [petertodd/checklocktimeverify-demos#2]
"create" works well but I have problems with spending.

When I hit
> hodl.py -v \<priv> \<timestamp> spend \<tx>:\<n> \<mynormaladdr>

I get

>Traceback (most recent call last):
>  File "C:\...\hodl.py", line 158, in <module>
>    args.cmd_func(args)
>  File "C:\...\hodl.py", line 101, in spend_command
>    prevout = proxy.gettxout(outpoint)
>  File "C:\Python34\lib\site-packages\bitcoin\rpc.py", line 466, in gettxout
>    r = self._call('gettxout', b2lx(outpoint.hash), outpoint.n, includemempool)
>  File "C:\Python34\lib\site-packages\bitcoin\rpc.py", line 184, in _call
>    'Content-type': 'application/json'})
>  File "C:\Python34\lib\http\client.py", line 1137, in request
>    self._send_request(method, url, body, headers)
>  File "C:\Python34\lib\http\client.py", line 1182, in _send_request
>    self.endheaders(body)
>  File "C:\Python34\lib\http\client.py", line 1133, in endheaders
>    self._send_output(message_body)
>  File "C:\Python34\lib\http\client.py", line 963, in _send_output
>    self.send(msg)
>  File "C:\Python34\lib\http\client.py", line 898, in send
>    self.connect()
>  File "C:\Python34\lib\http\client.py", line 871, in connect
>    self.timeout, self.source_address)
>  File "C:\Python34\lib\socket.py", line 516, in create_connection
>    raise err
>  File "C:\Python34\lib\socket.py", line 507, in create_connection
>    sock.connect(sa)
>ConnectionRefusedError: [WinError 10061]

I have Win7 x64, firewalls terminated, Bitcoin Core (bitcoin.conf with rpcpassword=) running from drive E:\... and symlink created from C:\...\Roaming\Bitcoin\ to that location (it's hard to have that 55gb blockchain on C:).
Are there any ways to get the raw spending transaction using your script without connections to Core?

**Comment by GilAlexander** [comment]
The problem was with bitcoin daemon I runned - I should check it more carefully using "bitcoin-cli getinfo". I got a typo in bitcoin.conf and server wasn't run properly - but bitcoin-qt started (I believed if there're problems with conf it will fail to start but not).

It's all right with the script.
