### ISSUE TITLE
mandatory-script-verify-flag-failed (Non-canonical DER signature)

### ISSUE THREAD

**Issue by sjStefan** [petertodd/checklocktimeverify-demos#4]
Broadcasting a raw-tx, which was generated by the script for the testnet produces the following error:

**error code: -26
error message:
16: mandatory-script-verify-flag-failed (Non-canonical DER signature)**

I´ve created the following address:

```
python2 hodl.py -t cR62Q2Dp8HriUXyKf1nYW6SYk6F1MZVMJbb2qqafCLBKSidV3SX3 1113520 create

2MsUY2M8gyWs2oJ56wcDo9MLdkjC5LW8HY4
```

After depositing 0.1 BTC on that address I´ve used the script to create the raw-tx to spend the coins:

```
python2 hodl.py -t cR62Q2Dp8HriUXyKf1nYW6SYk6F1MZVMJbb2qqafCLBKSidV3SX3 1113520 spend 5acfe3d5e2587f6c1b43a43b2d3f907b969b0bbd7b31c0f652553a5fca8f34ad:0 mmHhhBPx8qC8bQMAwSPcddsrfnaFhAXjyT

0100000001ad348fca5f3a5552f6c0317bbd0b9b967b903f2d3ba4431b6c7f58e2d5e3cf5a00000000754a30450221009bd5471f6d9fa5f733df788cd818c3a0497f68cf085b5f799b1615cb5bb052d202201d1e8e8eda581fedce145f08d580aec04f6f5ef78c07d741d5bcd5f3c451814e5b315d2903b0fd10b175210218a4b3a95f7b29bc9baf0c69835790af7aca065b38302c13d651972aa2bab3dbac0000000001706f9800000000001976a9143f4f289e811ae3001bfd0024e117ec6a2ab2945a88acb0fd1000
```

The decoded raw-tx looks like this:

```{
  "txid": "08a69cfd97d116975c4f82ac9cc2b8cb8286e42c0ceb47fb193472c9a3122915",
  "hash": "08a69cfd97d116975c4f82ac9cc2b8cb8286e42c0ceb47fb193472c9a3122915",
  "size": 202,
  "vsize": 202,
  "version": 1,
  "locktime": 1113520,
  "vin": [
    {
      "txid": "5acfe3d5e2587f6c1b43a43b2d3f907b969b0bbd7b31c0f652553a5fca8f34ad",
      "vout": 0,
      "scriptSig": {
        "asm": "30450221009bd5471f6d9fa5f733df788cd818c3a0497f68cf085b5f799b1615cb5bb052d202201d1e8e8eda581fedce145f08d580aec04f6f5ef78c07d741d5bcd5f3c451814e5b315d 03b0fd10b175210218a4b3a95f7b29bc9baf0c69835790af7aca065b38302c13d651972aa2bab3dbac",
        "hex": "4a30450221009bd5471f6d9fa5f733df788cd818c3a0497f68cf085b5f799b1615cb5bb052d202201d1e8e8eda581fedce145f08d580aec04f6f5ef78c07d741d5bcd5f3c451814e5b315d2903b0fd10b175210218a4b3a95f7b29bc9baf0c69835790af7aca065b38302c13d651972aa2bab3dbac"
      },
      "sequence": 0
    }
  ],
  "vout": [
    {
      "value": 0.09990000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 3f4f289e811ae3001bfd0024e117ec6a2ab2945a OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9143f4f289e811ae3001bfd0024e117ec6a2ab2945a88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mmHhhBPx8qC8bQMAwSPcddsrfnaFhAXjyT"
        ]
      }
    }
  ]
}
```

But sending this raw-tx leads to the error (mentioned above).
I´ve tried to broadcast with bitcoin core v.0.11.2 and v.0.13.1

I´ve also updated the python-bitcoinlib from v.0.5.0 to v.0.7.0 to see if that maybe fixes the issue, but without any changes.

I´ve started the hodl-script with python v.2.7.

After asking in IRC (channel: bitcoin) @harding helped me out a bit:

> (15:14:23) harding: 
sj_stefan: it's pretty weird. Your signature seems to be 75 bytes not including the sighash code, which I think is larger than signatures are supposed to be.  I don't see any problem with the code though.

For some reason, the same script has generated a raw-tx, that I was able to broadcast successfully last year (with bitcoin core v.0.11.0). Last time I´ve started the script without explicitly using a different python-version.

By just calling the hodl-script with the preferred python-version 3 now, I´m running into some python-errors, that doesn´t occur last year:

Traceback (most recent call last):
  File "/var/www/vhosts/service/classiccoin/cltv_origin/bitcoin/rpc.py", line 30, in <module>
    import http.client as httplib
ImportError: No module named 'http'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hodl.py", line 10, in <module>
    import bitcoin.rpc
  File "/var/www/vhosts/service/classiccoin/cltv_origin/bitcoin/rpc.py", line 32, in <module>
    import httplib
ImportError: No module named 'httplib'

**Comment by sjStefan** [comment]
Sticking to the recommended python v.3 and installing the missing python-libs/packages helped out. Sorry for bugging.
